name: dart_mystem

version: 0.1.0
homepage: https://github.com/nxtSwitch/dart_mystem
repository: https://github.com/nxtSwitch/dart_mystem
description: Wraps Yandex MyStem 3.1 in dart, and additionally provides a dart friendly API.

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: ^1.14.5
  pedantic: ^1.9.0
